updated

diff --git a/scripts/tmpl/get.besman.io.tmpl b/scripts/tmpl/get.besman.io.tmpl
--- a/scripts/tmpl/get.besman.io.tmpl
+++ b/scripts/tmpl/get.besman.io.tmpl
@@ -173,22 +173,45 @@ EOF
 		#return 1
 	fi
 
-	if [[ -z $(which ansible) ]]; then
-		echo "Installing ansible"
-		sudo apt-add-repository -y ppa:ansible/ansible
-		sudo apt update
-		sudo apt install ansible -y
+	if [ -z "$(which ansible)" ]; then
+
+		if echo "$BESMAN_SKIP_INSTALLABLES" | grep -q "ansible"; then
+			echo "Skipping ansible installation as per user request"
+		else
+			echo "Ansible not found. Installing Ansible..."
+			sudo apt-add-repository -y ppa:ansible/ansible
+			sudo apt update
+			sudo apt install ansible -y
+		fi
+
 	fi
 
 	if [[ -z $(which gh) ]]; then
-		echo "Installing GitHub Cli"
-		type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
-		curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
-		sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
-		echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
-		sudo apt update
-		sudo apt install gh -y
+		if echo "$BESMAN_SKIP_INSTALLABLES" | grep -q "gh"; then
+			echo "Skipping GitHub CLI(gh) installation as per user request"
+		else
+			echo "Installing GitHub Cli"
+			type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
+			curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+			sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
+			echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
+			sudo apt update
+			sudo apt install gh -y
+		fi
+	fi
 
+	if [[ -z $(which unzip) ]]; then
+		echo "Installing unzip"
+		sudo apt install unzip -y
+	fi
+
+	if [[ -z $(command -v jq) ]]; then
+		if echo "$BESMAN_SKIP_INSTALLABLES" | grep -q "jq"; then
+			echo "Skipping jq installation as per user request"
+		else
+			echo "Installing jq"
+			sudo apt update && sudo apt install jq -y
+		fi
 	fi
 
 	if [[ -z $(command -v pip) ]]; then
